## I3D features exploration

In [1]:
import scipy.io
import numpy as np

### Result from demo

In [2]:
import pickle as pkl

In [3]:
f_preds = open("../demo/results/predictions.pkl", "rb")
preds = pkl.load(f_preds)

features_demo = scipy.io.loadmat("../demo/results/features.mat")

In [50]:
len(preds)

110

In [57]:
features_demo["preds"].shape

(110, 1024)

### Features

In [6]:
features = scipy.io.loadmat("../data/features/bslcp/i3d_kinetics_bsl1k_bslcp_981/train/features.mat")

In [5]:
for key in features.keys():
	print(key)

__header__
__version__
__globals__
preds
clip_gt
clip_ix
video_names


In [7]:
preds = features["preds"]
clip_gt = features["clip_gt"]
clip_ix = features["clip_ix"]


In [30]:
preds.shape

(356378, 1024)

In [33]:
print(features["clip_gt"][0])
print(clip_gt[0].shape)


[array([[417, 691, 400, 698, 435, 298, 698,  81, 298, 698]])
 array([[417, 691, 400, 698, 435, 298, 698,  81, 298, 698]])
 array([[417, 691, 400, 698, 435, 298, 698,  81, 298, 698]]) ...
 array([[756, 679, 756, 412, 116, 698, 698]])
 array([[756, 679, 756, 412, 116, 698, 698]])
 array([[756, 679, 756, 412, 116, 698, 698]])]
(356378,)


In [8]:
print(features["clip_ix"][0])
print(features["clip_ix"][0].shape)
print(np.unique(features["clip_ix"][0]).shape)


# for i in range(100):
# 	print(clip_ix[0][i])


[   0    0    0 ... 5412 5412 5412]
(356378,)
(5413,)


In [16]:
5413*6.8

36808.4

In [9]:
for i in range(1000):
	print(i,"\t",  clip_ix[0][i],":", clip_gt[0][i][0])

0 	 0 : [417 691 400 698 435 298 698  81 298 698]
1 	 0 : [417 691 400 698 435 298 698  81 298 698]
2 	 0 : [417 691 400 698 435 298 698  81 298 698]
3 	 0 : [417 691 400 698 435 298 698  81 298 698]
4 	 0 : [417 691 400 698 435 298 698  81 298 698]
5 	 0 : [417 691 400 698 435 298 698  81 298 698]
6 	 0 : [417 691 400 698 435 298 698  81 298 698]
7 	 0 : [417 691 400 698 435 298 698  81 298 698]
8 	 0 : [417 691 400 698 435 298 698  81 298 698]
9 	 0 : [417 691 400 698 435 298 698  81 298 698]
10 	 0 : [417 691 400 698 435 298 698  81 298 698]
11 	 0 : [417 691 400 698 435 298 698  81 298 698]
12 	 0 : [417 691 400 698 435 298 698  81 298 698]
13 	 0 : [417 691 400 698 435 298 698  81 298 698]
14 	 0 : [417 691 400 698 435 298 698  81 298 698]
15 	 0 : [417 691 400 698 435 298 698  81 298 698]
16 	 0 : [417 691 400 698 435 298 698  81 298 698]
17 	 0 : [417 691 400 698 435 298 698  81 298 698]
18 	 0 : [417 691 400 698 435 298 698  81 298 698]
19 	 0 : [417 691 400 698 435 298 698  81

In [41]:
clip_gt[0][5412][0]

array([679, 756, 439, 604, 705, 585])

Check demo clip in features

In [58]:
uniques, counts = np.unique(features["clip_ix"][0], return_counts=True)

In [65]:
np.where(counts == 110)

(array([ 326,  419, 1210, 1436, 1563, 1588, 1937, 1976, 2717, 2747, 2780,
        3237, 3603, 3917, 4310, 4695, 4963, 5216, 5291, 5305]),)

In [ ]:
np.where(counts == 110)

(array([ 326,  419, 1210, 1436, 1563, 1588, 1937, 1976, 2717, 2747, 2780,
        3237, 3603, 3917, 4310, 4695, 4963, 5216, 5291, 5305]),)