In [1]:
import numpy as np
import torch

In [5]:
A = np.ones((10,2,100))
A[:,0,:] *= 2
torch.tensor(A)

tensor([[[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.]]], dtype=torch.float64)

In [11]:
A[:,0,:].shape

(10, 100)

In [15]:
B = torch.tensor(np.ones((10,3)))
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [17]:
B[:,:, None]

tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]], dtype=torch.float64)

In [21]:
torch.max(torch.rand((10,3)), dim = 1)


torch.return_types.max(
values=tensor([0.9183, 0.9004, 0.8649, 0.7409, 0.7512, 0.5826, 0.3898, 0.9246, 0.8778,
        0.5722]),
indices=tensor([0, 1, 2, 2, 1, 2, 0, 0, 0, 2]))

In [29]:
A = torch.rand((8,86,2))
A.shape

torch.Size([8, 86, 2])

In [30]:
A.view(-1, 2)


tensor([[0.4433, 0.2442],
        [0.9833, 0.5857],
        [0.0363, 0.7373],
        ...,
        [0.1361, 0.1410],
        [0.2438, 0.8427],
        [0.6861, 0.3900]])

In [32]:
A.permute(0,2,1).shape

torch.Size([8, 2, 86])